baseURL      = "https://samkang.github.io/mola-outputs/"
languageCode = "zh-tw"
title        = "mola-outputs ğŸŸ"

defaultContentLanguage = "zh-tw"
hasCJKLanguage = true

theme = "hugo-theme-stack"

[pagination]
    pagerSize = 5

[permalinks]
    # æ”¹å›æ¯”è¼ƒç›´è¦ºçš„ /posts/æª”å/ æ ¼å¼
    post = "/posts/:slug/"
    page = "/:slug/"
