baseURL      = "https://samkang.github.io/mola-outputs/"
languageCode = "zh-tw"
title        = "mola-outputs ğŸŸ"

# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "zh-tw"

# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage = true

theme = "hugo-theme-stack"

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
